"""LLM-judge validation for BERTopic topic models.

For each model passed via --models, samples representative abstracts per
topic, asks Gemini to score coherence / specificity / label_quality for
every topic, saves the raw + summarized results to topics/, and writes the
llm_* summary columns into topics/model_comparison.csv.

Run from inside 06_topic_modeling/ (same convention as the rest of the
pipeline):

    cd 06_topic_modeling
    python judge_validate.py --models scibert scincl specter2 --nr_topics auto

Note: the topic files currently checked into topics/ were generated with
--nr-topics auto (see topics/model_comparison.csv), so they are named
topics_<model>_auto.csv / doc_topics_<model>_auto.csv. Pass
--nr_topics auto to match them; pass a specific integer (e.g. 15) only once
topic files with that literal suffix exist.

Use --dry-run to print the exact prompt (system + user message) that would
be sent to Gemini for each requested model, without calling the API or
writing any output files.
"""

from __future__ import annotations

import argparse
import json
import os
import time
from pathlib import Path

import pandas as pd

import judge_config as cfg

SYSTEM_PROMPT = """You are an expert scientific topic modeling evaluator. You are evaluating the output
of a BERTopic model run on academic publications from NC State University (2006–2025),
covering agricultural and life sciences research.

For each topic you will receive:
- topic_id
- topic_label: comma-separated c-TF-IDF keywords generated by BERTopic
- subtopics: fine-grained subtopic keyword labels merged into this topic
- sample_abstracts: representative publication abstracts assigned to this topic

Score each topic on exactly three dimensions, from 1.0 to 5.0 (one decimal place):
  coherence     — Do the abstracts genuinely belong to the same research theme?
  specificity   — Is this a tight well-defined theme, or a vague catch-all?
  label_quality — Do the BERTopic keywords accurately reflect what the abstracts discuss?

Return ONLY valid JSON. No preamble, no explanation, no markdown fences.
Exact structure required:
{
  "model": "<model_name>",
  "topics": [
    {
      "topic_id": <int>,
      "topic_label": "<string>",
      "coherence": <float>,
      "specificity": <float>,
      "label_quality": <float>,
      "reasoning": "<one sentence max>"
    }
  ],
  "model_summary": {
    "mean_coherence": <float>,
    "mean_specificity": <float>,
    "mean_label_quality": <float>,
    "llm_overall": <float>
  }
}
llm_overall = mean of mean_coherence, mean_specificity, mean_label_quality."""


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--models", nargs="+", required=True,
                    help="Model names, e.g. scibert scincl specter2")
    p.add_argument("--nr_topics", default="auto",
                    help="Suffix used in topics_<model>_<nr_topics>.csv / "
                         "doc_topics_<model>_<nr_topics>.csv and matched against "
                         "the nr_topics column in model_comparison.csv. "
                         "Currently-generated files use 'auto' (default).")
    p.add_argument("--dry-run", action="store_true",
                    help="Print the prompt that would be sent for each model "
                         "and exit without calling the Gemini API or writing files.")
    return p.parse_args()


def load_pub_data() -> pd.DataFrame:
    df = pd.read_csv(cfg.PUB_DATA_PATH)
    if "Unnamed: 0" in df.columns:
        df = df.rename(columns={"Unnamed: 0": cfg.PUB_ID_COL})
    return df


def sample_size(topic_size: int) -> int:
    return min(cfg.SAMPLE_CAP, max(cfg.SAMPLE_FLOOR, round(topic_size * cfg.SAMPLE_PCT)))


def _clean(text) -> str:
    if pd.isna(text):
        return ""
    return str(text).replace("\n", " ").replace("\r", " ").strip()


def build_topic_samples(topics_df: pd.DataFrame, doc_topics_df: pd.DataFrame,
                         pub_df: pd.DataFrame) -> list[dict]:
    """Returns one dict per topic with sampled abstracts + formatting metadata."""
    topic_samples = []
    for _, topic_row in topics_df.iterrows():
        topic_id = topic_row[cfg.TOPIC_ID_COL]
        topic_size = int(topic_row[cfg.TOPIC_SIZE_COL])
        n = sample_size(topic_size)

        topic_pub_ids = doc_topics_df.loc[
            doc_topics_df[cfg.DOC_TOPIC_TOPIC_ID_COL] == topic_id,
            cfg.DOC_TOPIC_PUB_ID_COL,
        ]
        joined = pub_df[pub_df[cfg.PUB_ID_COL].isin(topic_pub_ids)][
            [cfg.PUB_ID_COL, cfg.TITLE_COL, cfg.ABSTRACT_COL]
        ]

        n_sample = min(n, len(joined))
        sampled = joined.sample(n=n_sample, random_state=cfg.RANDOM_SEED) if n_sample > 0 else joined

        papers_text = []
        for i, (_, row) in enumerate(sampled.iterrows(), start=1):
            title = _clean(row[cfg.TITLE_COL])
            abstract = _clean(row[cfg.ABSTRACT_COL])
            papers_text.append(f"    {i}. Title: {title}\n       Abstract: {abstract}")

        topic_samples.append({
            "topic_id": int(topic_id),
            "topic_label": topic_row[cfg.TOPIC_LABEL_COL],
            "subtopics": topic_row[cfg.SUBTOPICS_COL],
            "topic_size": topic_size,
            "n_sampled": n_sample,
            "papers_text": papers_text,
        })
    return topic_samples


def build_user_message(model_name: str, topic_samples: list[dict]) -> str:
    lines = [f"Model: {model_name}", ""]
    for ts in topic_samples:
        lines.append(f"Topic {ts['topic_id']}:")
        lines.append(f"  label: {ts['topic_label']}")
        lines.append(f"  subtopics: {ts['subtopics']}")
        lines.append(f"  sample abstracts ({ts['n_sampled']} of {ts['topic_size']} papers):")
        lines.extend(ts["papers_text"])
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def call_gemini(model_name: str, user_message: str) -> str:
    import google.generativeai as genai

    genai.configure(api_key=os.environ[cfg.GEMINI_API_KEY_ENV])
    gemini_model = genai.GenerativeModel(cfg.GEMINI_MODEL, system_instruction=SYSTEM_PROMPT)
    response = gemini_model.generate_content(user_message)
    return response.text


def parse_judge_json(raw_text: str) -> dict:
    text = raw_text.strip()
    if text.startswith("```"):
        text = text.strip("`")
        if text.startswith("json"):
            text = text[len("json"):]
    return json.loads(text.strip())


def update_model_comparison(model_name: str, nr_topics: str, model_summary: dict) -> None:
    comparison_path = Path(cfg.TOPICS_DIR) / "model_comparison.csv"
    df = pd.read_csv(comparison_path, dtype={"nr_topics": str})

    mask = (df["model"] == model_name) & (df["nr_topics"] == str(nr_topics))
    if not mask.any():
        print(f"[warn] no row for model={model_name}, nr_topics={nr_topics} in "
              f"{comparison_path} — skipping model_comparison update "
              f"(expected the row to already exist from run_topic_model.py)")
        return

    df.loc[mask, "llm_coherence"] = model_summary["mean_coherence"]
    df.loc[mask, "llm_specificity"] = model_summary["mean_specificity"]
    df.loc[mask, "llm_label_quality"] = model_summary["mean_label_quality"]
    df.loc[mask, "llm_overall"] = model_summary["llm_overall"]

    df.to_csv(comparison_path, index=False)
    print(f"[info] updated {comparison_path} for model={model_name}, nr_topics={nr_topics}")


def process_model(model_name: str, nr_topics: str, pub_df: pd.DataFrame, dry_run: bool) -> None:
    print(f"\n=== Model: {model_name} (nr_topics={nr_topics}) ===")

    topics_path = Path(cfg.TOPICS_DIR) / f"topics_{model_name}_{nr_topics}.csv"
    doc_topics_path = Path(cfg.TOPICS_DIR) / f"doc_topics_{model_name}_{nr_topics}.csv"

    if not topics_path.exists() or not doc_topics_path.exists():
        print(f"[error] missing input file(s) for model={model_name}: "
              f"{topics_path} exists={topics_path.exists()}, "
              f"{doc_topics_path} exists={doc_topics_path.exists()} — skipping")
        return

    topics_df = pd.read_csv(topics_path)
    doc_topics_df = pd.read_csv(doc_topics_path)

    topic_samples = build_topic_samples(topics_df, doc_topics_df, pub_df)
    for ts in topic_samples:
        print(f"[info] topic {ts['topic_id']}: sampled {ts['n_sampled']} of {ts['topic_size']} abstracts")

    user_message = build_user_message(model_name, topic_samples)

    if dry_run:
        print("\n--- SYSTEM PROMPT ---")
        print(SYSTEM_PROMPT)
        print("\n--- USER MESSAGE ---")
        print(user_message)
        return

    print(f"[info] calling Gemini ({cfg.GEMINI_MODEL}) for model={model_name}")
    try:
        raw_text = call_gemini(model_name, user_message)
    except Exception as e:
        print(f"[error] Gemini API call failed for model={model_name}: {e}")
        return

    try:
        parsed = parse_judge_json(raw_text)
    except json.JSONDecodeError as e:
        print(f"[error] failed to parse JSON response for model={model_name}: {e}")
        print("[debug] raw response text:")
        print(raw_text)
        return

    judge_topics_path = Path(cfg.TOPICS_DIR) / f"judge_topics_{model_name}.json"
    with open(judge_topics_path, "w") as f:
        json.dump(parsed, f, indent=2)
    print(f"[info] wrote {judge_topics_path}")

    model_summary = parsed.get("model_summary", {})
    judge_summary_path = Path(cfg.TOPICS_DIR) / f"judge_summary_{model_name}.json"
    with open(judge_summary_path, "w") as f:
        json.dump(model_summary, f, indent=2)
    print(f"[info] wrote {judge_summary_path}")

    update_model_comparison(model_name, nr_topics, model_summary)


def main() -> None:
    args = parse_args()
    pub_df = load_pub_data()
    print(f"[info] loaded {len(pub_df)} publications from {cfg.PUB_DATA_PATH}")

    for i, model_name in enumerate(args.models):
        process_model(model_name, args.nr_topics, pub_df, args.dry_run)
        if not args.dry_run and i < len(args.models) - 1:
            print(f"[info] sleeping {cfg.SLEEP_BETWEEN_CALLS}s before next model")
            time.sleep(cfg.SLEEP_BETWEEN_CALLS)


if __name__ == "__main__":
    main()
